// #include <erlang.idl>
//
// module erlang {
//     // an erlang binary
//     typedef sequence<octet> binary;
// };

interface DeltaZipExerciser {
    typedef sequence<octet> binary;

    struct MetadataItem {
        unsigned long keytag;
        binary value;
    };

    struct Version {
        binary content;
        sequence<MetadataItem> metadata;
    };

    typedef sequence <Version> Versions;

    binary add_to_archive(in binary archive, in Versions versions);
    Versions extract_all_versions(in binary archive);
};
