// #include <erlang.idl>;

module erlang {
    // an erlang binary
    typedef sequence<octet> binary;
};

interface DeltaZipExerciser {
    struct MetadataItem {
        unsigned long keytag;
        erlang::binary value;
    };

    struct Version {
        erlang::binary content;
        sequence<MetadataItem> metadata;
    };

    typedef sequence <Version> Versions;

    erlang::binary add_to_archive(in erlang::binary archive, in Versions versions);
    Versions extract_all_versions(in erlang::binary archive);
};
